package tv.lumo.android.core.auth.crypto

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.inject.Inject
import javax.inject.Singleton

/**
 * AES-256-GCM using a key held by the Android Keystore.
 *
 * The key never leaves the Keystore — on a device with a TEE or a StrongBox it
 * never leaves hardware at all. This class only ever handles a handle to it.
 * That is the whole point: a rooted device or a backup extraction yields the
 * ciphertext and not the key.
 *
 * **Why not `androidx.security:security-crypto`.** Jetpack Security is
 * deprecated and its `EncryptedFile`/`EncryptedSharedPreferences` were retired
 * rather than replaced. Twenty lines of platform API with an explicit format is
 * a smaller liability than a deprecated dependency, and it makes the envelope
 * layout reviewable — which matters, because getting GCM wrong is silent.
 *
 * Format: `iv (12 bytes) | ciphertext+tag`. The IV is generated by the provider
 * for every encryption, never reused, and stored in the clear alongside the
 * ciphertext, which is correct for GCM and required to decrypt.
 */
@Singleton
class KeystoreCipher @Inject constructor() {

    private val keyStore: KeyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }

    fun encrypt(plaintext: ByteArray): ByteArray {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, secretKey())
        val ciphertext = cipher.doFinal(plaintext)
        return cipher.iv + ciphertext
    }

    /**
     * @throws SessionUnreadableException when the blob cannot be decrypted —
     * truncated file, or a Keystore key that the system invalidated (a factory
     * reset, a restored backup, a lock-screen change on some devices). The
     * caller's only correct response is to drop the session and sign in again;
     * there is no recovering a session whose key is gone.
     */
    fun decrypt(envelope: ByteArray): ByteArray {
        if (envelope.size <= IV_LENGTH) {
            throw SessionUnreadableException("Stored session is truncated")
        }
        return try {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(
                Cipher.DECRYPT_MODE,
                secretKey(),
                GCMParameterSpec(TAG_LENGTH_BITS, envelope, 0, IV_LENGTH),
            )
            cipher.doFinal(envelope, IV_LENGTH, envelope.size - IV_LENGTH)
        } catch (e: java.security.GeneralSecurityException) {
            throw SessionUnreadableException("Stored session cannot be decrypted", e)
        }
    }

    private fun secretKey(): SecretKey {
        (keyStore.getEntry(KEY_ALIAS, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
        generator.init(
            KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(KEY_SIZE_BITS)
                // Deliberately NOT setUserAuthenticationRequired(true): the
                // television has no lock screen to authenticate against, and a
                // player that demands a fingerprint to resume is a player people
                // uninstall. The threat this defends against is offline
                // extraction, not a stranger holding an unlocked device.
                .setRandomizedEncryptionRequired(true)
                .build(),
        )
        return generator.generateKey()
    }

    private companion object {
        const val ANDROID_KEYSTORE = "AndroidKeyStore"
        const val KEY_ALIAS = "tv.lumo.session.v1"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val IV_LENGTH = 12
        const val TAG_LENGTH_BITS = 128
        const val KEY_SIZE_BITS = 256
    }
}

class SessionUnreadableException(
    message: String,
    cause: Throwable? = null,
) : Exception(message, cause)
